export const userTypes = {
  CREATE_USER: "CREATE_USER",
  LOGGIN_USER: "LOGGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_METHODS: "UPDATE_METHODS",
};

export const restaurantsTypes = {
  RESTAURANTS_GET: "RESTAURANTS_GET",
  RESTAURANT_FILTERED: "RESTAURANT_FILTERED",
  SET_RECENT_QUERIES: "SET_RECENT_QUERIES",
  RESTAURANTS_FILTERED: 'RESTAURANTS_FILTERED'
};
