export const userTypes = {
  CREATE_USER: "CREATE_USER",
  LOGGIN_USER: "LOGGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_METHODS: "UPDATE_METHODS",
};

export const restaurantsTypes = {
  RESTAURANTS_GET: "RESTAURANTS_GET",
};
